# Exploratory Data Analysis (EDA)

## Project: Smart Employee Salary Predictor

### Objective

The goal of this notebook is to understand the dataset before training a Machine Learning model.

We will:
- Load the dataset
- Inspect its structure
- Check for missing values
- Identify duplicate records
- Understand data types
- Generate summary statistics
- Explore categorical and numerical features

In [20]:
import pandas as pd
import numpy as np

In [21]:
df = pd.read_csv("../data/raw/salaries.csv")

In [22]:
df.head()

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2025,MI,FT,Research Scientist,208000,USD,208000,US,0,US,M
1,2025,MI,FT,Research Scientist,147000,USD,147000,US,0,US,M
2,2025,SE,FT,Research Scientist,173000,USD,173000,US,0,US,M
3,2025,SE,FT,Research Scientist,117000,USD,117000,US,0,US,M
4,2025,MI,FT,AI Engineer,100000,USD,100000,US,100,US,M

In [23]:
df.shape

(93597, 11)

In [24]:
df.columns

Index(['work_year', 'experience_level', 'employment_type', 'job_title',
       'salary', 'salary_currency', 'salary_in_usd', 'employee_residence',
       'remote_ratio', 'company_location', 'company_size'],
      dtype='object')

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93597 entries, 0 to 93596
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   work_year           93597 non-null  int64
 1   experience_level    93597 non-null  object
 2   employment_type     93597 non-null  object
 3   job_title           93597 non-null  object
 4   salary              93597 non-null  int64
 5   salary_currency     93597 non-null  object
 6   salary_in_usd       93597 non-null  int64
 7   employee_residence  93597 non-null  object
 8   remote_ratio        93597 non-null  int64
 9   company_location    93597 non-null  object
 10  company_size        93597 non-null  object
dtypes: int64(4), object(7)
memory usage: 7.9+ MB

In [26]:
df.describe()

          work_year        salary  salary_in_usd  remote_ratio
count  93597.000000  9.359700e+04   93597.000000  93597.000000
mean    2024.086434  1.623541e+05  157547.696774     21.455816
std        0.641449  2.221425e+05   73649.113729     40.954704
min     2020.000000  1.400000e+04   15000.000000      0.000000
25%     2024.000000  1.062600e+05  106250.000000      0.000000
50%     2024.000000  1.470000e+05  146232.000000      0.000000
75%     2024.000000  1.990000e+05  198000.000000      0.000000
max     2025.000000  3.040000e+07  800000.000000    100.000000

In [27]:
df.isnull().sum()

work_year             0
experience_level      0
employment_type       0
job_title             0
salary                0
salary_currency       0
salary_in_usd         0
employee_residence    0
remote_ratio          0
company_location      0
company_size          0
dtype: int64

In [28]:
df.duplicated().sum()

46960

In [29]:
df.nunique()

work_year                6
experience_level         4
employment_type          4
job_title              317
salary                8673
salary_currency         26
salary_in_usd         9535
employee_residence      96
remote_ratio             3
company_location        90
company_size             3
dtype: int64